{% set name = "acsconv" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ACSConv-{{ version }}.tar.gz
  sha256: 805a8525e2574a35238c91bc68463b6171591f7d5c7862c4d4cdfdaf293177eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - fire
    - matplotlib-base
    - numpy
    - pandas
    - python >={{ python_min }}
    - scikit-image
    - scikit-learn
    - scipy
    - tensorboardx
    - pytorch
    - torchvision
    - tqdm

test:
  imports:
    - acsconv
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/M3DV/ACSConv
  summary: 'Reinventing 2D Convolutions for 3D Images'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
